// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/server/rate_limiter.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowRequest) Reset() {
	*x = AllowRequest{}
	mi := &file_internal_server_rate_limiter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowRequest) ProtoMessage() {}

func (x *AllowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_rate_limiter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowRequest.ProtoReflect.Descriptor instead.
func (*AllowRequest) Descriptor() ([]byte, []int) {
	return file_internal_server_rate_limiter_proto_rawDescGZIP(), []int{0}
}

func (x *AllowRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type AllowResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Allowed         bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	RemainingTokens int32                  `protobuf:"varint,2,opt,name=remaining_tokens,json=remainingTokens,proto3" json:"remaining_tokens,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AllowResponse) Reset() {
	*x = AllowResponse{}
	mi := &file_internal_server_rate_limiter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowResponse) ProtoMessage() {}

func (x *AllowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_server_rate_limiter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowResponse.ProtoReflect.Descriptor instead.
func (*AllowResponse) Descriptor() ([]byte, []int) {
	return file_internal_server_rate_limiter_proto_rawDescGZIP(), []int{1}
}

func (x *AllowResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *AllowResponse) GetRemainingTokens() int32 {
	if x != nil {
		return x.RemainingTokens
	}
	return 0
}

var File_internal_server_rate_limiter_proto protoreflect.FileDescriptor

const file_internal_server_rate_limiter_proto_rawDesc = "" +
	"\n" +
	"\"internal/server/rate_limiter.proto\x12\vratelimiter\"+\n" +
	"\fAllowRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"T\n" +
	"\rAllowResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12)\n" +
	"\x10remaining_tokens\x18\x02 \x01(\x05R\x0fremainingTokens2M\n" +
	"\vRateLimiter\x12>\n" +
	"\x05Allow\x12\x19.ratelimiter.AllowRequest\x1a\x1a.ratelimiter.AllowResponseBFZDgithub.com/vishalpatel08/distributed-rate-limiter/internal/server/pbb\x06proto3"

var (
	file_internal_server_rate_limiter_proto_rawDescOnce sync.Once
	file_internal_server_rate_limiter_proto_rawDescData []byte
)

func file_internal_server_rate_limiter_proto_rawDescGZIP() []byte {
	file_internal_server_rate_limiter_proto_rawDescOnce.Do(func() {
		file_internal_server_rate_limiter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_server_rate_limiter_proto_rawDesc), len(file_internal_server_rate_limiter_proto_rawDesc)))
	})
	return file_internal_server_rate_limiter_proto_rawDescData
}

var file_internal_server_rate_limiter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_server_rate_limiter_proto_goTypes = []any{
	(*AllowRequest)(nil),  // 0: ratelimiter.AllowRequest
	(*AllowResponse)(nil), // 1: ratelimiter.AllowResponse
}
var file_internal_server_rate_limiter_proto_depIdxs = []int32{
	0, // 0: ratelimiter.RateLimiter.Allow:input_type -> ratelimiter.AllowRequest
	1, // 1: ratelimiter.RateLimiter.Allow:output_type -> ratelimiter.AllowResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_server_rate_limiter_proto_init() }
func file_internal_server_rate_limiter_proto_init() {
	if File_internal_server_rate_limiter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_server_rate_limiter_proto_rawDesc), len(file_internal_server_rate_limiter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_server_rate_limiter_proto_goTypes,
		DependencyIndexes: file_internal_server_rate_limiter_proto_depIdxs,
		MessageInfos:      file_internal_server_rate_limiter_proto_msgTypes,
	}.Build()
	File_internal_server_rate_limiter_proto = out.File
	file_internal_server_rate_limiter_proto_goTypes = nil
	file_internal_server_rate_limiter_proto_depIdxs = nil
}
